PROG	  = shift_test

COSIM 	 = vectors.o bare.o

LD	  = arc-linux-uclibc-ld
AS	  = arc-linux-uclibc-as

LD_SCRIPT = link_bare

AS_FLAGS  = -mA7 -mnorm -mswap -mmin_max -mEA
LD_FLAGS  = -T ${LD_SCRIPT} --print-map

${PROG}: ${PROG}.o ${COSIM} ${LD_SCRIPT}
	${LD} ${LD_FLAGS} -o ${PROG} ${PROG}.o ${COSIM} > ${PROG}.map

vectors.o: vectors.s
	${AS} ${AS_FLAGS} -o vectors.o vectors.s

bare.o:	bare.s
	${AS} ${AS_FLAGS} -o bare.o bare.s

${PROG}.o: ${PROG}.s
	${AS} ${AS_FLAGS} -o $@ $<

clean:
	rm -f ${PROG} *.o a.out *.map
